# Generated by Django 3.1 on 2022-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autoSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tTime', models.DateField()),
                ('client', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tradeEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tType', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=50)),
                ('lot', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('Deleted_by', models.CharField(max_length=50)),
                ('userIp', models.CharField(max_length=50)),
                ('oTime', models.DateField(auto_now_add=True)),
                ('dTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='userEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tType', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('lot', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('Deleted_by', models.CharField(max_length=50)),
                ('userIp', models.CharField(max_length=50)),
                ('oTime', models.DateField(auto_now_add=True)),
                ('dTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
