# Generated by Django 3.2.4 on 2022-06-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_useraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Partnership',
            field=models.CharField(default='5', max_length=100),
        ),
    ]
