# Generated by Django 3.2.4 on 2022-06-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_useraccount_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Remarks',
            field=models.CharField(max_length=100),
        ),
    ]
