# Generated by Django 3.2.4 on 2022-06-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useraccount_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='Card_Number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='Card_Type',
        ),
    ]
