# Generated by Django 3.2.4 on 2022-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220604_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Account_Code',
            field=models.CharField(max_length=50),
        ),
    ]
