# Generated by Django 3.2.4 on 2022-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_useraccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='creator',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
