# Generated by Django 3.2.4 on 2022-06-18 05:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_useraccount_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Alert',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Auto_Square',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Band_Script_Allow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Between_HighLow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Day_AutoSquare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='FOREX',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Brokerage Details': [], 'Margin Details': [], 'Other Details': []}),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Linked_with_Ledger',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='M2M_PL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='MCX',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Brokerage Details': [], 'Margin Details': [], 'Other Details': []}),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='NSE',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Brokerage Details': [], 'Margin Details': [], 'Other Details': []}),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Position_SquareOff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='segments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'segments': []}),
        ),
    ]
