# Generated by Django 3.2.4 on 2022-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220618_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='FOREX',
            field=models.JSONField(default={'Brokerage Details': [], 'Margin Details': [], 'Other Details': []}),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='MCX',
            field=models.JSONField(default={'Brokerage Details': [], 'Margin Details': [], 'Other Details': []}),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='NSE',
            field=models.JSONField(default={'Brokerage Details': [], 'Margin Details': [], 'Other Details': []}),
        ),
    ]
