# Generated by Django 3.2.4 on 2022-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220618_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='segments',
            field=models.JSONField(default={'segments': []}),
        ),
    ]
