# Generated by Django 3.2.4 on 2022-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_useraccount_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
    ]
